# Generated by Django 5.1.2 on 2026-01-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='is_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='limit_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='margin_mode',
            field=models.CharField(choices=[('ISOLATED', 'Isolated'), ('CROSS', 'Cross')], default='ISOLATED', max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='order_type',
            field=models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('STOP', 'Stop Loss'), ('STOP_LIMIT', 'Stop Limit')], default='MARKET', max_length=15),
        ),
        migrations.AddField(
            model_name='trade',
            name='trigger_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
