# Generated by Django 4.2.23 on 2025-09-10 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptionhistory",
            old_name="details",
            new_name="new_values",
        ),
        migrations.RemoveField(
            model_name="subscriptionhistory",
            name="action",
        ),
        migrations.AddField(
            model_name="subscriptionhistory",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="history_entries",
                to="subscriptions.coupon",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionhistory",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATED", "Subscription Created"),
                    ("RENEWED", "Subscription Renewed"),
                    ("CANCELLED", "Subscription Cancelled"),
                    ("EXPIRED", "Subscription Expired"),
                    ("UPDATED", "Subscription Updated"),
                    ("COUPON_APPLIED", "Coupon Applied"),
                    ("STATUS_CHANGED", "Status Changed"),
                ],
                default="UPDATED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionhistory",
            name="previous_values",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="subscriptionhistory",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionhistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="subscriptionhistory",
            index=models.Index(
                fields=["user", "event_type"], name="subscriptio_user_id_0e8537_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionhistory",
            index=models.Index(
                fields=["subscription", "event_type"],
                name="subscriptio_subscri_9d952c_idx",
            ),
        ),
    ]
