# Generated by Django 5.1.2 on 2026-02-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionorder_subscription_subscription_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionorder',
            name='order_type',
            field=models.CharField(choices=[('SELF_PURCHASED', 'Self Purchased'), ('ADMIN_ASSIGNED', 'Admin Assigned'), ('SYSTEM_GENERATED', 'System Generated'), ('B2B_REQUEST', 'B2B Request')], max_length=20),
        ),
    ]
