# Generated by Django 4.2.23 on 2025-09-24 06:21

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset_symbol", models.CharField(max_length=20)),
                ("asset_name", models.CharField(blank=True, max_length=100)),
                (
                    "asset_exchange",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "trade_type",
                    models.CharField(
                        choices=[
                            ("SPOT", "Spot"),
                            ("FUTURES", "Futures"),
                            ("OPTIONS", "Options"),
                            ("CFD", "Contract for Difference"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("PARTIALLY_CLOSED", "Partially Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "holding_type",
                    models.CharField(
                        choices=[
                            ("INTRADAY", "Intraday"),
                            ("SWING", "Swing"),
                            ("LONGTERM", "Long Term"),
                        ],
                        default="INTRADAY",
                        max_length=10,
                    ),
                ),
                (
                    "total_quantity",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "remaining_quantity",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "average_price",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "total_invested",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_trades",
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=30
                    ),
                ),
                (
                    "total_invested",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=30
                    ),
                ),
                (
                    "total_realized_pnl",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=30
                    ),
                ),
                (
                    "total_unrealized_pnl",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=30
                    ),
                ),
                (
                    "total_return_percentage",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "day_pnl",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=30
                    ),
                ),
                (
                    "day_pnl_percentage",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("active_trades_count", models.IntegerField(default=0)),
                ("total_trades_count", models.IntegerField(default=0)),
                ("winning_trades_count", models.IntegerField(default=0)),
                ("losing_trades_count", models.IntegerField(default=0)),
                (
                    "max_drawdown",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_portfolios",
            },
        ),
        migrations.CreateModel(
            name="OptionsDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        choices=[("CALL", "Call"), ("PUT", "Put")], max_length=4
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=5
                    ),
                ),
                ("strike_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("expiry_date", models.DateField()),
                ("premium", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "trade",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options_details",
                        to="trading.trade",
                    ),
                ),
            ],
            options={
                "db_table": "options_details",
            },
        ),
        migrations.CreateModel(
            name="FuturesDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leverage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=5
                    ),
                ),
                (
                    "margin_required",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "margin_used",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("expiry_date", models.DateField()),
                (
                    "contract_size",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1"), max_digits=20
                    ),
                ),
                ("is_hedged", models.BooleanField(default=False)),
                (
                    "trade",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="futures_details",
                        to="trading.trade",
                    ),
                ),
            ],
            options={
                "db_table": "futures_details",
            },
        ),
        migrations.CreateModel(
            name="TradeHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("BUY", "Buy"),
                            ("SELL", "Sell"),
                            ("PARTIAL_SELL", "Partial Sell"),
                            ("CANCEL", "Cancel"),
                            ("MODIFY", "Modify"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("MARKET", "Market"),
                            ("LIMIT", "Limit"),
                            ("STOP", "Stop Loss"),
                            ("STOP_LIMIT", "Stop Limit"),
                        ],
                        default="MARKET",
                        max_length=15,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "realized_pnl",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="trading.trade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trade_history",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="trade_histo_user_id_6c9082_idx",
                    ),
                    models.Index(
                        fields=["trade", "created_at"],
                        name="trade_histo_trade_i_a4b8fe_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="trade_histo_action_6f93f2_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["user", "status"], name="user_trades_user_id_53e9d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["asset_symbol", "trade_type"],
                name="user_trades_asset_s_7608f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["user", "asset_symbol", "trade_type", "status"],
                name="user_trades_user_id_e4a91b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["user", "opened_at"], name="user_trades_user_id_5881dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["asset_symbol", "status"], name="user_trades_asset_s_9d299b_idx"
            ),
        ),
    ]
