# Generated by Django 4.2.23 on 2025-10-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("mark_price", models.DecimalField(decimal_places=8, max_digits=15)),
                ("ltp", models.DecimalField(decimal_places=8, max_digits=15)),
                ("high", models.DecimalField(decimal_places=8, max_digits=15)),
                ("low", models.DecimalField(decimal_places=8, max_digits=15)),
                ("volume", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "price_history",
            },
        ),
    ]
