# Generated by Django 4.2.23 on 2026-01-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengeweek",
            name="min_futures_trades",
            field=models.PositiveIntegerField(
                default=0, help_text="Minimum futures trades required"
            ),
        ),
        migrations.AddField(
            model_name="challengeweek",
            name="min_options_trades",
            field=models.PositiveIntegerField(
                default=0, help_text="Minimum options trades required"
            ),
        ),
        migrations.AddField(
            model_name="challengeweek",
            name="min_spot_trades",
            field=models.PositiveIntegerField(
                default=0, help_text="Minimum spot trades required"
            ),
        ),
        migrations.AlterField(
            model_name="challengeweek",
            name="min_trades_required",
            field=models.PositiveIntegerField(
                default=5, help_text="Total minimum trades required"
            ),
        ),
    ]
