# Generated by Django 4.2.23 on 2026-01-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0002_challengeweek_min_futures_trades_and_more"),
    ]

    operations = [
        # Add default values to the database columns
        migrations.RunSQL(
            sql=[
                "ALTER TABLE challenge_weeks ALTER COLUMN min_spot_trades SET DEFAULT 0;",
                "ALTER TABLE challenge_weeks ALTER COLUMN min_futures_trades SET DEFAULT 0;",
                "ALTER TABLE challenge_weeks ALTER COLUMN min_options_trades SET DEFAULT 0;",
                # Update existing NULL values to 0
                "UPDATE challenge_weeks SET min_spot_trades = 0 WHERE min_spot_trades IS NULL;",
                "UPDATE challenge_weeks SET min_futures_trades = 0 WHERE min_futures_trades IS NULL;",
                "UPDATE challenge_weeks SET min_options_trades = 0 WHERE min_options_trades IS NULL;",
            ],
            reverse_sql=[
                "ALTER TABLE challenge_weeks ALTER COLUMN min_spot_trades DROP DEFAULT;",
                "ALTER TABLE challenge_weeks ALTER COLUMN min_futures_trades DROP DEFAULT;",
                "ALTER TABLE challenge_weeks ALTER COLUMN min_options_trades DROP DEFAULT;",
            ],
        ),
    ]
