# Generated by Django 4.2.23 on 2026-01-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0003_add_defaults_to_trade_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchallengereward",
            name="behavioral_tag",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userchallengereward",
            name="reward_type",
            field=models.CharField(
                choices=[
                    ("PROFIT_BONUS", "Profit Bonus"),
                    ("LOSS_RECOVERY", "Loss Recovery"),
                    ("EXCELLENCE_BONUS", "Excellence Bonus"),
                ],
                default="PROFIT_BONUS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userchallengereward",
            name="total_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
