# Generated by Django 4.2.23 on 2026-01-29 09:09

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0004_userchallengereward_behavioral_tag_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeEvaluationReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_discipline_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("completed_mandatory_tasks", models.IntegerField(default=0)),
                ("total_mandatory_tasks", models.IntegerField(default=0)),
                (
                    "trading_discipline_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "trade_count_subscore",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "asset_class_subscore",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "overtrading_penalty",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "profit_outcome_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "consistency_bonus_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "tier_name",
                    models.CharField(
                        choices=[
                            ("BRONZE", "Bronze (Beginner)"),
                            ("SILVER", "Silver (Intermediate)"),
                            ("GOLD", "Gold (Advanced)"),
                            ("PLATINUM", "Platinum (Elite)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "behavior_tag",
                    models.CharField(
                        choices=[
                            ("DISCIPLINED", "Disciplined"),
                            ("BALANCED", "Balanced"),
                            ("AGGRESSIVE", "Aggressive"),
                            ("EMOTIONAL", "Emotional"),
                            ("RECKLESS", "Reckless"),
                            ("INCONSISTENT", "Inconsistent"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "key_issue",
                    models.TextField(blank=True, help_text="One sentence diagnosis"),
                ),
                (
                    "next_challenge_focus",
                    models.JSONField(
                        default=list, help_text="List of 3 focus rules for next time"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_report",
                        to="challenge.userchallengeparticipation",
                    ),
                ),
            ],
            options={
                "db_table": "challenge_evaluation_reports",
                "ordering": ["-generated_at"],
            },
        ),
    ]
