# Generated by Django 5.1.2 on 2026-02-05 08:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_challengeevaluationreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeweek',
            name='max_drawdown_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='Max drawdown % allowed', max_digits=5),
        ),
        migrations.AddField(
            model_name='challengeweek',
            name='max_leverage_allowed',
            field=models.PositiveIntegerField(default=1, help_text='Max leverage allowed (e.g. 1 for Spot, 5 for low-risk, 20 for high-risk)'),
        ),
        migrations.AddField(
            model_name='challengeweek',
            name='min_win_rate_required',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Min win rate % required to pass', max_digits=5),
        ),
    ]
