# Generated by Django 4.2.23 on 2025-08-18 12:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("phone_verified", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                ("two_factor_enabled", models.BooleanField(default=False)),
                ("security_notifications", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "account_user_profile",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelOptions(
            name="userloginhistory",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Login History",
                "verbose_name_plural": "Login History",
            },
        ),
        migrations.AlterModelOptions(
            name="usersession",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
            },
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="account_use_mobile_6a0dc0_idx",
            old_name="users_mobile_6f2369_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="account_use_role_f4255b_idx",
            old_name="users_role_0ace22_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="account_use_is_acti_428f36_idx",
            old_name="users_is_acti_847b48_idx",
        ),
        migrations.RenameIndex(
            model_name="usersession",
            new_name="account_use_user_id_ea8106_idx",
            old_name="user_sessio_user_id_bb1b83_idx",
        ),
        migrations.RenameIndex(
            model_name="usersession",
            new_name="account_use_session_71c859_idx",
            old_name="user_sessio_session_cc84b9_idx",
        ),
        migrations.AddField(
            model_name="userloginhistory",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userloginhistory",
            name="country_code",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="userloginhistory",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(
                db_index=True,
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mobile number format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user_admin", "User Admin"),
                    ("b2b_admin", "B2B Admin"),
                    ("b2b_user", "B2B User"),
                    ("b2c_user", "B2C User"),
                ],
                db_index=True,
                default="b2c_user",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userloginhistory",
            name="email_attempted",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="userloginhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("failed_credentials", "Failed - Invalid Credentials"),
                    ("failed_locked", "Failed - Account Locked"),
                    ("failed_inactive", "Failed - Account Inactive"),
                    ("failed_verification", "Failed - Email Not Verified"),
                    ("failed_rate_limit", "Failed - Rate Limited"),
                    ("failed_suspicious", "Failed - Suspicious Activity"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userloginhistory",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="userloginhistory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="login_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="termination_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("logout", "User Logout"),
                    ("timeout", "Session Timeout"),
                    ("forced", "Forced Termination"),
                    ("security", "Security Reason"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="account_use_email_553b8f_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["date_joined"], name="account_use_date_jo_403b71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userloginhistory",
            index=models.Index(
                fields=["user", "timestamp"], name="account_use_user_id_4c6ffb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userloginhistory",
            index=models.Index(
                fields=["email_attempted", "timestamp"],
                name="account_use_email_a_11c323_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userloginhistory",
            index=models.Index(
                fields=["status", "timestamp"], name="account_use_status_47b4d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userloginhistory",
            index=models.Index(
                fields=["ip_address", "timestamp"],
                name="account_use_ip_addr_3d92e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["created_at"], name="account_use_created_099306_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["expires_at"], name="account_use_expires_f95b40_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="account_user",
        ),
        migrations.AlterModelTable(
            name="userloginhistory",
            table="account_user_login_history",
        ),
        migrations.AlterModelTable(
            name="usersession",
            table="account_user_sessions",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
