# Generated by Django 4.2.23 on 2025-08-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_userprofile_alter_user_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="two_factor_enabled",
        ),
    ]
