# Generated by Django 4.2.23 on 2025-08-18 13:37

import apps.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_userprofile_two_factor_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="expires_at",
            field=models.DateTimeField(
                default=apps.account.models.default_session_expiry
            ),
        ),
    ]
