# Generated by Django 5.1.4 on 2025-08-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_usersession_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("b2b_admin", "B2B Admin"),
                    ("b2b_user", "B2B User"),
                    ("b2c_user", "B2C User"),
                ],
                db_index=True,
                default="b2c_user",
                max_length=20,
            ),
        ),
    ]
