# Generated by Django 5.1.2 on 2026-02-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_session_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
