# Generated by Django 4.2.23 on 2025-10-07 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("CREDIT", "Credit"),
                            ("DEBIT", "Debit"),
                            ("BLOCK", "Block"),
                            ("UNBLOCK", "Unblock"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "account_wallet_transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="account_wal_user_id_95f3f5_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "created_at"],
                        name="account_wal_transac_b3e3b2_idx",
                    ),
                    models.Index(
                        fields=["user", "transaction_type"],
                        name="account_wal_user_id_ebbf2a_idx",
                    ),
                ],
            },
        ),
    ]
