# Generated by Django 4.2.23 on 2025-09-15 10:05

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "subscriptions",
            "0002_rename_details_subscriptionhistory_new_values_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("ADMIN_ASSIGNED", "Admin Assigned"),
                            ("SELF_PURCHASED", "Self Purchased"),
                            ("SYSTEM", "System Generated"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="External payment transaction ID for future payment integration",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original plan price",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Discount amount from coupon",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final amount after discount (amount - discount)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When subscription should start (defaults to now for completed orders)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the order"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "subscription_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscription_source",
            field=models.CharField(
                choices=[
                    ("ADMIN_ASSIGNED", "Admin Assigned"),
                    ("SELF_PURCHASED", "Self Purchased"),
                    ("SYSTEM", "System Generated"),
                ],
                default="SELF_PURCHASED",
                help_text="How this subscription was created",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionhistory",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATED", "Subscription Created"),
                    ("RENEWED", "Subscription Renewed"),
                    ("CANCELLED", "Subscription Cancelled"),
                    ("EXPIRED", "Subscription Expired"),
                    ("UPDATED", "Subscription Updated"),
                    ("COUPON_APPLIED", "Coupon Applied"),
                    ("STATUS_CHANGED", "Status Changed"),
                    ("ORDER_CREATED", "Order Created"),
                    ("ORDER_COMPLETED", "Order Completed"),
                    ("ORDER_CANCELLED", "Order Cancelled"),
                    ("ORDER_FAILED", "Order Failed"),
                ],
                default="UPDATED",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["subscription_source"], name="subscriptio_subscri_ac0e69_idx"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionorder",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="subscriptions.coupon",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionorder",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="subscriptions.plan",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionorder",
            index=models.Index(
                fields=["user", "status"], name="subscriptio_user_id_ef26cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionorder",
            index=models.Index(
                fields=["order_type", "status"], name="subscriptio_order_t_c2c598_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionorder",
            index=models.Index(
                fields=["created_at"], name="subscriptio_created_eca9c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionorder",
            index=models.Index(
                fields=["transaction_id"], name="subscriptio_transac_bf3cb7_idx"
            ),
        ),
    ]
